import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync, existsSync } from "fs";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = (process.argv[2] === "production");

// Load .env file for build-time defaults
function loadEnv() {
    const envPath = ".env";
    const envVars = {};
    if (existsSync(envPath)) {
        const content = readFileSync(envPath, "utf-8");
        for (const line of content.split("\n")) {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith("#")) continue;
            const eqIndex = trimmed.indexOf("=");
            if (eqIndex === -1) continue;
            const key = trimmed.substring(0, eqIndex).trim();
            const value = trimmed.substring(eqIndex + 1).trim();
            envVars[key] = value;
        }
    }
    return envVars;
}

const envVars = loadEnv();

// Build define map: process.env.KEY -> "value"
const define = {};
for (const [key, value] of Object.entries(envVars)) {
    define[`process.env.${key}`] = JSON.stringify(value);
}

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    define,
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
