// Re-export all types
export * from './team';
export * from './document';
export * from './report';

// Plugin settings type
export interface TeamPluginSettings {
    // Server settings
    serverUrl: string;
    wsUrl: string;
    apiKey: string;

    // User info
    userId: string;
    username: string;

    // Current team
    currentTeamId: string;

    // AI settings
    aiProvider: AIProviderType;
    aiApiKey: string;
    aiEndpoint: string;
    aiModel: string;

    // Report settings
    dailyReportTemplate: string;
    monthlyReportTemplate: string;
    autoGenerateDailyReport: boolean;
    dailyReportTime: string; // HH:mm format

    // Sync settings
    syncPluginList: boolean;
    syncPluginSettings: boolean;
    excludedPlugins: string[];

    // General
    language: 'zh' | 'en';
    debugMode: boolean;
}

export type AIProviderType = 'openai' | 'claude' | 'dmxapi' | 'custom';

export const DEFAULT_SETTINGS: TeamPluginSettings = {
    serverUrl: process.env.SERVER_URL || '',
    wsUrl: process.env.WS_URL || '',
    apiKey: '',
    userId: '',
    username: '',
    currentTeamId: '',
    aiProvider: (process.env.AI_PROVIDER as AIProviderType) || 'dmxapi',
    aiApiKey: '',
    aiEndpoint: process.env.AI_ENDPOINT || '',
    aiModel: process.env.AI_MODEL || 'gpt-4',
    dailyReportTemplate: '',
    monthlyReportTemplate: '',
    autoGenerateDailyReport: false,
    dailyReportTime: '18:00',
    syncPluginList: true,
    syncPluginSettings: true,
    excludedPlugins: [],
    language: 'zh',
    debugMode: false,
};
